Add zuul CI integration
opentelekomcloud-infra/customer-service-monitoring pull request #269
Opened 2020-12-16 17:07 UTC by outcatcher

Add linters for python and ansible

Update playbooks requirements

Resolve #266

2020-12-16 18:18 UTC, lego963 requested changes
Change ansible version in readme pls

2020-12-16 18:18 UTC, lego963 commented on playbooks/files/requirements.txt
> +ocomone== 0.4.3
Remove space after ==

2020-12-16 20:09 UTC, outcatcher commented
recheck

2020-12-17 07:50 UTC, anton-sidelnikov approved these changes

2020-12-17 07:51 UTC, lego963 approved these changes

2020-12-17 08:30 UTC, anton-sidelnikov submitted a review, later dismissed

2020-12-17 08:30 UTC, lego963 approved these changes, later dismissed

2020-12-17 09:08 UTC, outcatcher commented
recheck

2020-12-17 10:55 UTC, anton-sidelnikov approved these changes

2020-12-17 10:55 UTC, lego963 approved these changes

2020-12-17 11:08 UTC, lego963 commented
regate

2020-12-17 11:11 UTC, merged