Rds backup monitoring
opentelekomcloud-infra/customer-service-monitoring pull request #295
Opened 2020-12-24 13:30 UTC by Polina-Gubina

2020-12-24 13:41 UTC, outcatcher requested changes

2020-12-24 13:41 UTC, outcatcher commented on playbooks/rds_backup_monitoring_setup.yml
> +        name:
It's better to move python requirements to `requirements.txt`, e.g. `rds-requirements.txt`

2020-12-24 13:41 UTC, outcatcher commented on playbooks/rds_backup_monitoring_setup.yml
> +      file: dest=/tmp/rds/check_rds_filling_status.sh mode=a+x
Why are you using single-line syntax here?

2020-12-24 13:41 UTC, outcatcher commented on playbooks/rds_backup_monitoring_setup.yml
> +      shell: "start-stop-daemon -Sbmvp /tmp/rds/__main__.pid -x /usr/bin/python3 /tmp/rds/__main__.py -- `
Why are you not using multiline `>` string?

2020-12-24 13:41 UTC, outcatcher commented on playbooks/rds_backup_monitoring_setup.yml
> +        job: "/tmp/rds/check_rds_filling_status.sh `
Same as previous

2020-12-24 13:41 UTC, outcatcher commented on playbooks/rds_backup_monitoring_setup.yml
> +        dest: /tmp/rds/
You use `/tmp/rds/` in multiple places. Please use variable.

2020-12-24 13:41 UTC, outcatcher commented on playbooks/rds_backup_monitoring_setup.yml
> +                  }
Missing new-line at the end of the file.

2020-12-24 13:41 UTC, outcatcher commented on playbooks/rds_backup_monitoring_setup.yml
> +    terraform_workspace: prod
`terraform_workspace` is defined in the inventory, please do not rewrite it here

2020-12-24 13:41 UTC, outcatcher commented on scenarios/rds_backup_monitoring/settings.tf
> +  cloud = "devstack"
To make testing easier, please pass the cloud name as `OS_CLOUD` env var instead of provider argument.

2020-12-24 13:41 UTC, outcatcher commented on scenarios/rds_backup_monitoring/infrastructure.tf
> +}
Missing new line at the end of file

2020-12-29 14:21 UTC, outcatcher requested changes

2020-12-29 14:21 UTC, outcatcher commented on playbooks/rds_backup_monitoring_destroy.yml
> +    OS_CLOUD: "devstack"
Please use `lookup('env', 'OS_CLOUD')`

2020-12-29 14:21 UTC, outcatcher commented on playbooks/rds_backup_monitoring_setup.yml
> +    OS_CLOUD: "devstack"
Same as previous

2020-12-30 08:40 UTC, lego963 requested changes

2020-12-30 08:40 UTC, lego963 commented on playbooks/rds_backup_monitoring_setup.yml
> +                  }
remove whitespaces

2020-12-30 08:40 UTC, lego963 commented on scenarios/rds_backup_monitoring/variables.tf
> +variable "addr_3" { default = "192.168.0" }
remove or fix addr_3 octets

2020-12-30 10:27 UTC, lego963 commented on playbooks/rds_backup_monitoring_setup.yml
> +      shell: "start-stop-daemon -Sbmvp {{ test_scripts_path }}/__main__.pid \
can we make like in 129 line without `\`?

2020-12-30 10:38 UTC, anton-sidelnikov requested changes

2020-12-30 10:38 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +    - name: Install PIP, rsync libpq-dev and python-dev
rsync

2020-12-30 10:38 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +    - name: Schedule load script status check
wrong task name

2020-12-30 10:38 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +    - name: Schedule load script status check
Schedule RDS script status check

2020-12-30 10:39 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +    - name: Install PIP, rsync libpq-dev and python-dev
remove it from name pls

2020-12-30 14:28 UTC, anton-sidelnikov submitted a review, later dismissed

2020-12-30 17:11 UTC, lego963 submitted a review, later dismissed

2020-12-31 07:27 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_destroy.yml
> +  hosts: localhost
test_host

2020-12-31 07:28 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +  hosts: localhost
test_host

2020-12-31 07:28 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +        pg_port: "{{ hostvars.localhost.db_port }}"
hostvars.test_host

2020-12-31 07:28 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +        pg_db_url: "{{ hostvars.localhost.db_address }}"
hostvars.test_host

2020-12-31 07:29 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +              address: "postgres://{{ hostvars.localhost.db_username }}\
hostvars.test_host

2020-12-31 07:29 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +              :{{ hostvars.localhost.db_password }}@{{ hostvars.localhost.db_address }}/entities"
hostvars.test_host

2020-12-31 07:29 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +               --instance_id {{ hostvars.localhost.rds_instance_id }}
hostvars.test_host

2020-12-31 07:29 UTC, anton-sidelnikov commented on playbooks/rds_backup_monitoring_setup.yml
> +               --cloud_name {{ hostvars.localhost.cloud_name }}
hostvars.test_host

2020-12-31 07:52 UTC, lego963 commented on playbooks/rds_backup_monitoring_setup.yml
> +    TF_VAR_psql_password: "Spasibo2020!"
Spaciba2020!

2020-12-31 08:41 UTC, anton-sidelnikov submitted a review, later dismissed

2020-12-31 08:42 UTC, lego963 approved these changes

2020-12-31 08:43 UTC, outcatcher approved these changes

2020-12-31 08:43 UTC, anton-sidelnikov approved these changes

2020-12-31 08:57 UTC, merged