Fix linter issues
opentelekomcloud-infra/customer-service-monitoring pull request #302
Opened 2020-12-26 10:39 UTC by lego963

2020-12-26 18:43 UTC, anton-sidelnikov requested changes

2020-12-26 18:43 UTC, anton-sidelnikov commented on playbooks/lb_monitoring_setup.yml
>            -o ProxyCommand='ssh -W %h:%p -q linux@{{ controller_public_ip }}
Why proxy command duplicated?

2020-12-26 18:43 UTC, anton-sidelnikov commented on playbooks/lb_monitoring_setup.yml
>            -o ProxyCommand='ssh -W %h:%p -q linux@{{ controller_public_ip }}
Here

2020-12-26 18:43 UTC, anton-sidelnikov commented on playbooks/dns_monitoring_setup.yml
> +          -o ProxyCommand='ssh -W %h:%p -q linux@{{ controller_public_ip }}
And here

2020-12-26 20:34 UTC, outcatcher commented
Why this PR contains changes to `scripts/terraform-lint.sh`?

2020-12-26 20:35 UTC, outcatcher requested changes
Why this PR contains changes to scripts/terraform-lint.sh?

2020-12-26 20:36 UTC, outcatcher commented on playbooks/lb_monitoring_setup.yml
> +      shell: "nohup python3 -m csm_test_utils monitor --target {{ elb_ip }} --telegraf 'http://{{ bastion_ip }}' &"
Lint error, please use multi-line (`>`) string here

2020-12-27 14:21 UTC, Polina-Gubina approved these changes, later dismissed

2020-12-27 20:23 UTC, lego963 commented
> Why this PR contains changes to scripts/terraform-lint.sh?

because script terraform.sh didn't work at all

2020-12-27 20:26 UTC, lego963 commented on playbooks/lb_monitoring_setup.yml
>            -o ProxyCommand='ssh -W %h:%p -q linux@{{ controller_public_ip }}
I copied this from `devel` branch

2020-12-28 07:29 UTC, outcatcher commented
> > Why this PR contains changes to scripts/terraform-lint.sh?
> 
> because script `terraform.sh` didn't work at all
> `ubuntu-bionic | ./scripts/terraform-lint.sh: 6: Syntax error: "(" unexpected`

Wow, that's strange. Seems the bash version differs from the one I've tested with. I will make a fix for that in #303

2020-12-28 08:56 UTC, lego963 commented
recheck

2020-12-28 13:49 UTC, anton-sidelnikov approved these changes

2020-12-28 13:51 UTC, outcatcher requested changes

2020-12-28 13:51 UTC, outcatcher commented on .zuul.yaml
> -    voting: false
Kets nake them voting in another PR

2020-12-28 13:53 UTC, lego963 commented on .zuul.yaml
> -    voting: false
I have lint fixes, maybe here?

2020-12-28 14:23 UTC, outcatcher approved these changes

2020-12-28 14:28 UTC, merged