Update lb_down_test.sh
opentelekomcloud-infra/customer-service-monitoring pull request #314
Opened 2020-12-29 12:44 UTC by lego963

2020-12-29 13:53 UTC, outcatcher approved these changes

2020-12-29 14:11 UTC, anton-sidelnikov submitted a review, later dismissed

2020-12-30 07:46 UTC, outcatcher requested changes

2020-12-30 07:46 UTC, outcatcher commented on playbooks/files/lb_down_test.sh
> +ssh-add "${test_folder}/key_csm_controller"
Let's use an env variable for key name

2020-12-30 07:46 UTC, outcatcher commented on playbooks/files/lb_down_test.sh
> +  cd "${test_folder}" || exit
Please specify exit code, the default one is `0`

2020-12-30 07:46 UTC, outcatcher commented on playbooks/files/lb_down_test.sh
> +  ansible-playbook -i inventory/prod ${playbook}
Please add `|| exit 1` here

2020-12-30 09:08 UTC, Polina-Gubina approved these changes

2020-12-30 09:20 UTC, outcatcher approved these changes, later dismissed

2020-12-30 09:25 UTC, Polina-Gubina approved these changes, later dismissed

2020-12-30 10:08 UTC, anton-sidelnikov approved these changes

2020-12-30 10:33 UTC, merged