Use `cidrsubnet` and `cidrhost` in scenarios and modules
opentelekomcloud-infra/customer-service-monitoring pull request #317
Opened 2020-12-30 10:07 UTC by outcatcher

Fix #277 Get rid of `addr_3_octets`

Setting `network_cidr` variable is required now

2020-12-30 13:51 UTC, lego963 requested changes
then you have to change defavult values of `addr_3_octet` in `*.tfvars`

2020-12-30 14:20 UTC, anton-sidelnikov requested changes

2020-12-30 14:20 UTC, anton-sidelnikov commented on scenarios/modules/ecs_node/vm.tf
> +    ip_address = var.node_local_ip
how it works with multiple nodes?

2020-12-30 14:26 UTC, anton-sidelnikov requested changes

2020-12-30 14:26 UTC, anton-sidelnikov commented on scenarios/lb_monitoring/infrastructure.tf
> +  lb_local_ip      = cidrhost(local.scenario_subnet, 1)
cidrhost(local.scenario_subnet, 3)

2020-12-30 14:39 UTC, anton-sidelnikov submitted a review, later dismissed

2020-12-30 18:59 UTC, Polina-Gubina commented on scenarios/csm_controller/terraform.tfvars
> +network_cidr      = "192.168.0.0/16"
network_cidr = "{{ terraform_network_cidr }}" ?

2020-12-30 19:07 UTC, Polina-Gubina submitted a review, later dismissed

2020-12-31 09:03 UTC, outcatcher commented
recheck

2020-12-31 09:29 UTC, anton-sidelnikov approved these changes

2020-12-31 09:32 UTC, outcatcher commented
recheck

2020-12-31 09:52 UTC, Polina-Gubina approved these changes

2020-12-31 10:12 UTC, lego963 approved these changes

2020-12-31 10:22 UTC, merged