Add variable kms_key to all scenario where it is required
opentelekomcloud-infra/customer-service-monitoring pull request #340
Opened 2021-01-19 08:44 UTC by Polina-Gubina

2021-01-19 11:06 UTC, Polina-Gubina commented
recheck

2021-01-22 07:53 UTC, anton-sidelnikov requested changes

2021-01-22 07:53 UTC, anton-sidelnikov commented on inventory/prod/group_vars/all.yaml
> +kms_key: kms_key
csm_kms_key

2021-01-22 08:00 UTC, lego963 approved these changes

2021-01-22 08:02 UTC, anton-sidelnikov approved these changes

2021-01-22 08:10 UTC, merged