Ansible role for preparing localhost
opentelekomcloud-infra/customer-service-monitoring pull request #358
Opened 2021-02-11 13:39 UTC by Polina-Gubina

Ansible role for preparing localhost

2021-02-11 13:56 UTC, anton-sidelnikov requested changes

2021-02-11 13:56 UTC, anton-sidelnikov commented on roles/prepare_local/files/requirements.txt
>  ansible-lint>=4.1.0
less than 5

2021-02-11 13:56 UTC, anton-sidelnikov commented on roles/prepare_local/defaults/main.yaml
> +scenario_name: ""
call role prepare_build

2021-02-11 14:36 UTC, outcatcher requested changes

2021-02-11 14:36 UTC, outcatcher commented on roles/prepare_build/files/requirements.txt
> +ansible-lint>5
Should be  `ansible-lint>=4.1.0,<5.0`

2021-02-12 13:27 UTC, outcatcher submitted a review, later dismissed

2021-02-16 13:24 UTC, anton-sidelnikov submitted a review, later dismissed

2021-02-17 06:49 UTC, closed without merging