Move loadbalancer tf module to ansible role for crearing lb
opentelekomcloud-infra/customer-service-monitoring pull request #363
Opened 2021-02-17 13:52 UTC by Polina-Gubina

Move loadbalancer tf module to ansible role for crearing lb

2021-02-17 14:04 UTC, outcatcher requested changes

2021-02-17 14:04 UTC, outcatcher commented on roles/loadbalancer/tasks/build.yaml
> +    name: "{{ scenario_name }}_member_{{ my_idx|int +1 }}"
There is no need for +1 index

2021-02-17 14:04 UTC, outcatcher commented on roles/loadbalancer/tasks/destroy.yaml
> +  with_sequence: start=1 end="{{ loadblcr_members_count|int  }}"
Why in build loop is used and here with_sequence?

2021-02-17 14:04 UTC, outcatcher commented on roles/loadbalancer/defaults/main.yaml
> +loadblcr_instances: ""
Lets make count 2 by default

2021-02-17 14:04 UTC, outcatcher commented on roles/loadbalancer/defaults/main.yaml
> +loadbalancer_members_count: ""
Isn't it equal to instance count?

2021-02-19 07:43 UTC, anton-sidelnikov approved these changes

2021-02-19 07:46 UTC, outcatcher approved these changes

2021-02-19 08:15 UTC, merged