Bastion role
opentelekomcloud-infra/customer-service-monitoring pull request #365
Opened 2021-02-20 12:13 UTC by Polina-Gubina

Role for building bastion

2021-02-20 12:23 UTC, outcatcher requested changes

2021-02-20 12:23 UTC, outcatcher commented on inventory/prod/group_vars/all.yaml
> +subnet_cidr: "{{ network_cidr }}"
Just `network_cidr` should be used in case it's equal to `subnet_cidr`

2021-02-20 12:23 UTC, outcatcher commented on inventory/prod/group_vars/all.yaml
> +key_path: "{{ tmp_dir }}/{{ key_name }}"
Duplicates `local_private_key`

2021-02-20 12:23 UTC, outcatcher commented on playbooks/lb_monitoring_setup.yaml
> +    server_port: 8
Final newline is missing

2021-02-20 12:23 UTC, outcatcher commented on playbooks/vars/lb_monitoring.yaml
> +loadbalancer_scenario_name: "loadbalancer_prefix"
What is the difference between `loadbalancer_scenario_name` and `scenario`?

2021-02-20 12:23 UTC, outcatcher commented on roles/bastion/defaults/main.yaml
> +bastion_key_pair_name: ""
Shouln't `bastion_key_pair_name` be set to `key_name`?

2021-02-20 12:23 UTC, outcatcher commented on playbooks/vars/lb_monitoring.yaml
> +loadbalancer_subnet_cidr: "{{ subnet_cidr | ansible.netcommon.ipsubnet('24', 1) }}"
Instead of `subnet_cidr` there should be `network_cidr`

2021-02-20 12:23 UTC, outcatcher commented on roles/bastion/tasks/build.yaml
> +  register: bastion
Missing the final newline

2021-02-20 12:23 UTC, outcatcher commented on roles/csm_controller/defaults/main.yaml
>  keypair_name: ""
Is `keypair_name` same as `key_name`?

2021-02-20 12:23 UTC, outcatcher commented on roles/public_router/defaults/main.yaml
> +subnet_cidr: "192.168.0.0/16"
This equals to `network_cidr` from the inventory

2021-02-24 07:53 UTC, anton-sidelnikov approved these changes

2021-02-24 07:56 UTC, anton-sidelnikov requested changes

2021-02-24 07:56 UTC, anton-sidelnikov commented on roles/bastion/tasks/build.yaml
> +    auto_ip: true
set private ip to 192.168.0.2

2021-02-24 11:15 UTC, Polina-Gubina commented
recheck

2021-02-24 12:35 UTC, anton-sidelnikov submitted a review, later dismissed

2021-02-24 13:08 UTC, anton-sidelnikov submitted a review, later dismissed

2021-02-24 13:29 UTC, Polina-Gubina commented
recheck

2021-02-24 13:32 UTC, outcatcher approved these changes

2021-02-24 13:41 UTC, anton-sidelnikov approved these changes

2021-02-24 14:13 UTC, merged