Get rid of subgroups in inventory
opentelekomcloud-infra/customer-service-monitoring pull request #381
Opened 2021-04-02 14:34 UTC by Polina-Gubina

Get rid of subgroups in inventory

2021-04-06 14:26 UTC, anton-sidelnikov requested changes

2021-04-06 14:26 UTC, anton-sidelnikov commented on inventory/extended/main.yaml
> +      secgroup_tcp_ports: ["22", "80", "443", "2003", "2004", "2023", "2024", "8126"]
["22", "80", "443"]

2021-04-06 14:26 UTC, anton-sidelnikov commented on inventory/extended/main.yaml
> +      secgroup_udp_ports: ["8126"]
[]

2021-04-06 14:26 UTC, anton-sidelnikov commented on playbooks/lb_monitoring_destroy.yaml
> +    - name: Include variables required for lm monitoring infra
lb not lm

2021-04-06 14:26 UTC, anton-sidelnikov commented on playbooks/lb_monitoring_setup.yaml
> +    - name: Include variables required for lm monitoring infra
lm monitoring -> lb monitoring

2021-04-06 14:28 UTC, anton-sidelnikov requested changes

2021-04-06 14:28 UTC, anton-sidelnikov commented on playbooks/public_router.yaml
> +    vpcs_info: "{{ vpcs_info | default({}) | \combine( {vpc_name: \
strange thing

2021-04-06 15:21 UTC, anton-sidelnikov approved these changes, later dismissed

2021-04-07 09:42 UTC, lego963 commented
recheck

2021-04-07 13:05 UTC, lego963 commented
recheck

2021-04-07 14:45 UTC, anton-sidelnikov approved these changes

2021-04-07 15:38 UTC, merged