check metadata monitoring
opentelekomcloud-infra/customer-service-monitoring pull request #397
Opened 2021-04-22 14:24 UTC by anton-sidelnikov

2021-04-22 14:30 UTC, Polina-Gubina approved these changes, later dismissed

2021-04-22 14:54 UTC, lego963 submitted a review, later dismissed

2021-04-22 15:13 UTC, outcatcher requested changes

2021-04-22 15:13 UTC, outcatcher commented on playbooks/files/metadata/get_metadata.py
> +        metric_name = f'{args["statsd_prefix"]}.{args["metric_name"]}.{socket.gethostname()}'
Double assignment

2021-04-22 15:22 UTC, Polina-Gubina submitted a review, later dismissed

2021-04-22 15:36 UTC, outcatcher approved these changes, later dismissed

2021-04-22 16:05 UTC, lego963 approved these changes, later dismissed

2021-04-23 09:57 UTC, Polina-Gubina approved these changes

2021-04-23 10:03 UTC, outcatcher approved these changes

2021-04-23 11:44 UTC, merged